# Generated by Django 4.1.5 on 2023-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100, unique=True)),
                ('password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'AdminDetails',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendence_id', models.CharField(default=None, max_length=100, null=True)),
                ('Teacher_ID', models.CharField(default=None, max_length=100, null=True)),
                ('Current_Date', models.CharField(default=None, max_length=100, null=True)),
                ('Current_Time', models.CharField(default=None, max_length=100, null=True)),
                ('Student_ID', models.CharField(default=None, max_length=100, null=True)),
                ('Subject', models.CharField(default=None, max_length=100, null=True)),
                ('Login_Time', models.CharField(default=None, max_length=100, null=True)),
                ('Logout_Time', models.CharField(default=None, max_length=100, null=True)),
                ('Login_Status', models.CharField(default=None, max_length=100, null=True)),
                ('Logout_Status', models.CharField(default=None, max_length=100, null=True)),
                ('login_type', models.CharField(default=None, max_length=100, null=True)),
                ('Semester', models.CharField(default=None, max_length=3, null=True)),
            ],
            options={
                'db_table': 'Attendence',
            },
        ),
        migrations.CreateModel(
            name='Attendance_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendence_id', models.CharField(default=None, max_length=100, null=True)),
                ('Today_date', models.CharField(default=None, max_length=100, null=True)),
                ('Teacher_ID', models.CharField(default=None, max_length=100, null=True)),
                ('Current_Date', models.CharField(default=None, max_length=100, null=True)),
                ('Current_Time', models.CharField(default=None, max_length=100, null=True)),
                ('Student_ID', models.CharField(default=None, max_length=100, null=True)),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('Subject', models.CharField(default=None, max_length=100, null=True)),
                ('Login_Time', models.CharField(default=None, max_length=100, null=True)),
                ('Logout_Time', models.CharField(default=None, max_length=100, null=True)),
                ('Login_Status', models.CharField(default=None, max_length=100, null=True)),
                ('Logout_Status', models.CharField(default=None, max_length=100, null=True)),
                ('login_type', models.CharField(default=None, max_length=100, null=True)),
                ('Semester', models.CharField(default=None, max_length=3, null=True)),
                ('Attendance_status', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Attendence_New',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Id', models.CharField(default=None, max_length=100, null=True)),
                ('Subject', models.CharField(default=None, max_length=100, null=True)),
                ('Day', models.CharField(default=None, max_length=100, null=True)),
                ('Time', models.CharField(default=None, max_length=100, null=True)),
                ('Semester', models.IntegerField()),
            ],
            options={
                'db_table': 'Lab',
            },
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('Age', models.CharField(default=None, max_length=3, null=True)),
                ('Gender', models.CharField(default=None, max_length=100, null=True)),
                ('Department', models.CharField(default=None, max_length=100, null=True)),
                ('Semester', models.CharField(default=None, max_length=100, null=True)),
                ('Barcode', models.CharField(default=None, max_length=5, unique=True)),
                ('Barcode_Assigned', models.CharField(default=None, max_length=100, null=True)),
                ('Dept_assigned', models.CharField(default=None, max_length=100, null=True)),
                ('Subject', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('username', models.CharField(default=None, max_length=100, null=True, unique=True)),
                ('Gender', models.CharField(default=None, max_length=100, null=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
                ('Semester', models.CharField(default=None, max_length=100, null=True)),
                ('Subject', models.CharField(default=None, max_length=100, null=True)),
                ('Department', models.CharField(default=None, max_length=100, null=True)),
                ('Dept_assigned', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Teacher_Details',
            },
        ),
    ]
