# Generated by Django 4.1.5 on 2023-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Barcode',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='attendance_new',
            name='Barcode',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Semester',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
