# Generated by Django 4.1.5 on 2023-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0003_alter_attendance_new_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='Time',
        ),
        migrations.AddField(
            model_name='lab',
            name='End_time',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='Start_time',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
