# Generated by Django 4.1.5 on 2023-04-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0004_remove_lab_time_lab_end_time_lab_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_new',
            name='Hour',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
