# Generated by Django 4.2 on 2023-04-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0005_attendance_new_hour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='Barcode_Assigned',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='Dept_assigned',
        ),
    ]
