# Generated by Django 4.2 on 2023-04-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0006_delete_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_new',
            name='Hour',
        ),
    ]
