# Generated by Django 4.2 on 2023-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0007_remove_attendance_new_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_id', models.CharField(default=None, max_length=100, null=True)),
                ('sem_name', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(default=None, max_length=100, null=True)),
                ('sem_id', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
    ]
