# Generated by Django 4.2 on 2023-04-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0008_semesters_subjects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semesters',
            table='Semesters',
        ),
    ]
