# Generated by Django 4.2 on 2023-04-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0009_alter_semesters_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesters',
            name='Dept',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='Dept',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
