# Generated by Django 4.2 on 2023-04-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0010_semesters_dept_subjects_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesters',
            name='Dept',
        ),
        migrations.RemoveField(
            model_name='semesters',
            name='sem_name',
        ),
    ]
