# Generated by Django 4.2 on 2023-04-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0011_remove_semesters_dept_remove_semesters_sem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semesters',
            old_name='sem_id',
            new_name='sem',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='sem_id',
            new_name='sem',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='sub_name',
            new_name='sub',
        ),
    ]
