# Generated by Django 4.2 on 2023-04-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0012_rename_sem_id_semesters_sem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='SubSem',
        ),
        migrations.DeleteModel(
            name='Semesters',
        ),
        migrations.RenameField(
            model_name='subsem',
            old_name='sub',
            new_name='subs',
        ),
        migrations.AlterModelTable(
            name='subsem',
            table='subsem',
        ),
    ]
